backend:
  name: "git-gateway"
  branch: "main"
publish_mode: "editorial_workflow"
media_folder: "src/assets/uploads"
# public_folder: "/assets/uploads"
collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "src/pages/posts"
    create: true
    delete: true
    fields:
      - name: "layout"
        widget: "hidden"
        label: "Layout"
        default: "../../layouts/MarkdownPostLayout.astro"
      - name: "title"
        widget: "string"
        label: "Title"
      - name: "pubDate"
        widget: "datetime"
        label: "Published date"
      - name: "description"
        widget: "string"
        label: "Description"
        required: false
      - name: "author"
        widget: "string"
        label: "Author"
      - name: "featured_image"
        widget: "image"
        label: "Featured Image"
        choose_url: true
        required: false
      - name: "images"
        widget: "list"
        label: "Images"
        required: false
        fields: 
          - {label: "Image", name: "url", choose_url: true, media_folder: "src/assets/uploads", widget: "image"}
          - {label: "Alt text", name: "alt", widget: "string"}
      - name: "tags"
        widget: "list"
        label: "Tags"
        required: false
        fields: 
          - {label: "Tag", name: "tag", widget: "string"}
      - name: "body"
        widget: "markdown"
        label: "Body"
  - name: "special-services"
    label: "Special Services"
    folder: "src/pages/services/special"
    create: true
    delete: true
    fields:
      - name: "layout"
        widget: "hidden"
        label: "Layout"
        default: "../../layouts/MarkdownPostLayout.astro"
      - name: "title"
        widget: "string"
        label: "Title"
      - name: "pubDate"
        widget: "datetime"
        label: "Published date"
      - name: "description"
        widget: "string"
        label: "Description"
        required: false
      - name: "author"
        widget: "string"
        label: "Author"
      - name: "featured_image"
        widget: "image"
        label: "Featured Image"
        choose_url: true
        required: false
      - name: "images"
        widget: "list"
        label: "Images"
        required: false
        fields: 
          - {label: "Image", name: "url", choose_url: true, media_folder: "src/assets/uploads", widget: "image"}
          - {label: "Alt text", name: "alt", widget: "string"}
      - name: "tags"
        widget: "list"
        label: "Tags"
        required: false
        fields: 
          - {label: "Tag", name: "tag", widget: "string", required: false}
      - name: "body"
        widget: "markdown"
        label: "Body"